version: '3.9'
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  django:
    image: django-docker:0.0.1
    build: .
    command: python3 outtask/manage.py runserver
    ports:
      - "8000:8000"
    depends_on:
      - db